// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    int32_t capacity;
    int32_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef int32_t (*ForeignCallback)(uint64_t, int32_t, const uint8_t *_Nonnull, int32_t, RustBuffer *_Nonnull);

// Task defined in Rust that Swift executes
typedef void (*UniFfiRustTaskCallback)(const void * _Nullable, int8_t);

// Callback to execute Rust tasks using a Swift Task
//
// Args:
//   executor: ForeignExecutor lowered into a size_t value
//   delay: Delay in MS
//   task: UniFfiRustTaskCallback to call
//   task_data: data to pass the task callback
typedef int8_t (*UniFfiForeignExecutorCallback)(size_t, uint32_t, UniFfiRustTaskCallback _Nullable, const void * _Nullable);

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H

// Continuation callback for UniFFI Futures
typedef void (*UniFfiRustFutureContinuation)(void * _Nonnull, int8_t);

// Scaffolding functions
int8_t uniffi_sdk_fn_func_address_is_valid(RustBuffer network, RustBuffer address, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_sdk_fn_func_address_to_x_coordinate(RustBuffer network, RustBuffer address, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_sdk_fn_func_authorize_transaction(RustBuffer network, RustBuffer private_key, RustBuffer program, RustBuffer function, RustBuffer inputs, double fee_credits, RustBuffer fee_record, RustBuffer imports, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_sdk_fn_func_decrypt_ciphertext(RustBuffer network, RustBuffer view_key, RustBuffer ciphertext, RustBuffer tpk, RustBuffer program_id, RustBuffer function_name, uint64_t index, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_sdk_fn_func_decrypt_record(RustBuffer network, RustBuffer view_key, RustBuffer record_ciphertext, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_sdk_fn_func_decrypt_transition(RustBuffer network, RustBuffer view_key, RustBuffer transition, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_sdk_fn_func_encrypt_record(RustBuffer network, RustBuffer view_key, RustBuffer record_plaintext, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_sdk_fn_func_execute_authorization(RustBuffer network, RustBuffer authorization_json, RustBuffer fee_authorization_json, RustBuffer program, RustBuffer imports, RustBuffer function, RustBuffer rest_endpoint, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_sdk_fn_func_from_seed_unchecked(RustBuffer network, RustBuffer seed, RustCallStatus *_Nonnull out_status
);
int8_t uniffi_sdk_fn_func_is_record_owner(RustBuffer network, RustBuffer view_key, RustBuffer address_x_coordinate, RustBuffer record_nonce, RustBuffer record_owner_x_coordinate, RustCallStatus *_Nonnull out_status
);
int8_t uniffi_sdk_fn_func_owns_transition(RustBuffer network, RustBuffer view_key, RustBuffer tpk_str, RustBuffer tcm_str, RustCallStatus *_Nonnull out_status
);
int8_t uniffi_sdk_fn_func_private_key_is_valid(RustBuffer network, RustBuffer private_key, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_sdk_fn_func_private_key_new(RustBuffer network, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_sdk_fn_func_private_key_to_address(RustBuffer network, RustBuffer private_key, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_sdk_fn_func_private_key_to_view_key(RustBuffer network, RustBuffer private_key, RustCallStatus *_Nonnull out_status
);
int8_t uniffi_sdk_fn_func_program_is_valid(RustBuffer network, RustBuffer program, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_sdk_fn_func_program_to_id(RustBuffer network, RustBuffer program, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_sdk_fn_func_serial_number_string(RustBuffer network, RustBuffer record_plaintext, RustBuffer private_key, RustBuffer program_id, RustBuffer record_name, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_sdk_fn_func_sign(RustBuffer network, RustBuffer private_key, RustBuffer message, RustCallStatus *_Nonnull out_status
);
int8_t uniffi_sdk_fn_func_verify(RustBuffer network, RustBuffer signature, RustBuffer message, RustBuffer address, RustCallStatus *_Nonnull out_status
);
int8_t uniffi_sdk_fn_func_view_key_is_valid(RustBuffer network, RustBuffer view_key, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_sdk_fn_func_view_key_to_address(RustBuffer network, RustBuffer view_key, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_sdk_rustbuffer_alloc(int32_t size, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_sdk_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
void ffi_sdk_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_sdk_rustbuffer_reserve(RustBuffer buf, int32_t additional, RustCallStatus *_Nonnull out_status
);
void ffi_sdk_rust_future_continuation_callback_set(UniFfiRustFutureContinuation _Nonnull callback
);
void ffi_sdk_rust_future_poll_u8(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_sdk_rust_future_cancel_u8(void* _Nonnull handle
);
void ffi_sdk_rust_future_free_u8(void* _Nonnull handle
);
uint8_t ffi_sdk_rust_future_complete_u8(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_sdk_rust_future_poll_i8(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_sdk_rust_future_cancel_i8(void* _Nonnull handle
);
void ffi_sdk_rust_future_free_i8(void* _Nonnull handle
);
int8_t ffi_sdk_rust_future_complete_i8(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_sdk_rust_future_poll_u16(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_sdk_rust_future_cancel_u16(void* _Nonnull handle
);
void ffi_sdk_rust_future_free_u16(void* _Nonnull handle
);
uint16_t ffi_sdk_rust_future_complete_u16(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_sdk_rust_future_poll_i16(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_sdk_rust_future_cancel_i16(void* _Nonnull handle
);
void ffi_sdk_rust_future_free_i16(void* _Nonnull handle
);
int16_t ffi_sdk_rust_future_complete_i16(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_sdk_rust_future_poll_u32(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_sdk_rust_future_cancel_u32(void* _Nonnull handle
);
void ffi_sdk_rust_future_free_u32(void* _Nonnull handle
);
uint32_t ffi_sdk_rust_future_complete_u32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_sdk_rust_future_poll_i32(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_sdk_rust_future_cancel_i32(void* _Nonnull handle
);
void ffi_sdk_rust_future_free_i32(void* _Nonnull handle
);
int32_t ffi_sdk_rust_future_complete_i32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_sdk_rust_future_poll_u64(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_sdk_rust_future_cancel_u64(void* _Nonnull handle
);
void ffi_sdk_rust_future_free_u64(void* _Nonnull handle
);
uint64_t ffi_sdk_rust_future_complete_u64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_sdk_rust_future_poll_i64(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_sdk_rust_future_cancel_i64(void* _Nonnull handle
);
void ffi_sdk_rust_future_free_i64(void* _Nonnull handle
);
int64_t ffi_sdk_rust_future_complete_i64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_sdk_rust_future_poll_f32(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_sdk_rust_future_cancel_f32(void* _Nonnull handle
);
void ffi_sdk_rust_future_free_f32(void* _Nonnull handle
);
float ffi_sdk_rust_future_complete_f32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_sdk_rust_future_poll_f64(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_sdk_rust_future_cancel_f64(void* _Nonnull handle
);
void ffi_sdk_rust_future_free_f64(void* _Nonnull handle
);
double ffi_sdk_rust_future_complete_f64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_sdk_rust_future_poll_pointer(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_sdk_rust_future_cancel_pointer(void* _Nonnull handle
);
void ffi_sdk_rust_future_free_pointer(void* _Nonnull handle
);
void*_Nonnull ffi_sdk_rust_future_complete_pointer(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_sdk_rust_future_poll_rust_buffer(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_sdk_rust_future_cancel_rust_buffer(void* _Nonnull handle
);
void ffi_sdk_rust_future_free_rust_buffer(void* _Nonnull handle
);
RustBuffer ffi_sdk_rust_future_complete_rust_buffer(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_sdk_rust_future_poll_void(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_sdk_rust_future_cancel_void(void* _Nonnull handle
);
void ffi_sdk_rust_future_free_void(void* _Nonnull handle
);
void ffi_sdk_rust_future_complete_void(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
uint16_t uniffi_sdk_checksum_func_address_is_valid(void
    
);
uint16_t uniffi_sdk_checksum_func_address_to_x_coordinate(void
    
);
uint16_t uniffi_sdk_checksum_func_authorize_transaction(void
    
);
uint16_t uniffi_sdk_checksum_func_decrypt_ciphertext(void
    
);
uint16_t uniffi_sdk_checksum_func_decrypt_record(void
    
);
uint16_t uniffi_sdk_checksum_func_decrypt_transition(void
    
);
uint16_t uniffi_sdk_checksum_func_encrypt_record(void
    
);
uint16_t uniffi_sdk_checksum_func_execute_authorization(void
    
);
uint16_t uniffi_sdk_checksum_func_from_seed_unchecked(void
    
);
uint16_t uniffi_sdk_checksum_func_is_record_owner(void
    
);
uint16_t uniffi_sdk_checksum_func_owns_transition(void
    
);
uint16_t uniffi_sdk_checksum_func_private_key_is_valid(void
    
);
uint16_t uniffi_sdk_checksum_func_private_key_new(void
    
);
uint16_t uniffi_sdk_checksum_func_private_key_to_address(void
    
);
uint16_t uniffi_sdk_checksum_func_private_key_to_view_key(void
    
);
uint16_t uniffi_sdk_checksum_func_program_is_valid(void
    
);
uint16_t uniffi_sdk_checksum_func_program_to_id(void
    
);
uint16_t uniffi_sdk_checksum_func_serial_number_string(void
    
);
uint16_t uniffi_sdk_checksum_func_sign(void
    
);
uint16_t uniffi_sdk_checksum_func_verify(void
    
);
uint16_t uniffi_sdk_checksum_func_view_key_is_valid(void
    
);
uint16_t uniffi_sdk_checksum_func_view_key_to_address(void
    
);
uint32_t ffi_sdk_uniffi_contract_version(void
    
);
